Update README.md
nmajor25/companies-hiring-remote-devs pull request #2
Opened 2022-09-06 15:11 UTC by brian-rutherford

Added U-Haul

2022-09-16 06:01 UTC, nmajor25 requested changes
Cool! Didn't know U-Haul hires remote developers.

We can remove your last column that contains this: `Fully remote teams hiring anywhere in the United States`. 

The location is already specified via your `USA` column.

Appreciate the contribution 😄

2022-09-16 15:53 UTC, brian-rutherford commented
I can remove that, I saw others (like Tune) with similar wording - "Remote first company and embraces hiring engineers and various other roles across the United States & Canada."

2022-09-17 18:38 UTC, nmajor25 commented
Ah... ya good call. I'll go through and clean those up.

2022-09-17 18:38 UTC, nmajor25 approved these changes

2022-09-17 18:39 UTC, merged